### ISSUE TITLE
DemoController doesn't exist in current context

### ISSUE THREAD

**Issue by nicolarohde** [BrianHooper/cwu-cs-advising#1]
Demo controller has a problem on the Index page.

![error](https://user-images.githubusercontent.com/28128915/36652504-ea3de6b6-1a63-11e8-99f0-2a57a9260898.PNG)

**Comment by nicolarohde** [comment]
Also happens on other pages, maybe the constructor for demo controller was taken/commented out during today's session?

**Comment by BrianHooper** [comment]
I deleted DemoController like a week ago, that was just for the midterm presentation. All the code that used it should be updated already. Maybe the published code got an old version somehow? Index.cshtml doesn't even have a select tag anymore.

**Comment by nicolarohde** [comment]
Some files aren't marked for recompilation.  
Solution:
1. Save .ini file somewhere
2. Delete publish folder. 
3. Recompile with (for hosting dlls): dotnet publish -c Debug -r debian-x64
4. Recompile with (for release dlls): dotnet publish -c Release -r debian-x64
5. Add .ini file back to publish folder.
